---
sudo: required
dist: trusty

language: python
python: "2.7"

env:
  - ANSIBLE_VERSION=latest
  - ANSIBLE_VERSION=2.0.1.0
  - ANSIBLE_VERSION=2.0.0.2
  - ANSIBLE_VERSION=2.0.0.1
  - ANSIBLE_VERSION=2.0.0.0
  - ANSIBLE_VERSION=1.9.4
  - ANSIBLE_VERSION=1.9.3
  - ANSIBLE_VERSION=1.9.2
  - ANSIBLE_VERSION=1.9.1
  - ANSIBLE_VERSION=1.9.0.1
  - ANSIBLE_VERSION=1.8.4
  - ANSIBLE_VERSION=1.8.3
  - ANSIBLE_VERSION=1.8.2
  - ANSIBLE_VERSION=1.8.1
  - ANSIBLE_VERSION=1.8
  - ANSIBLE_VERSION=1.7.2
  - ANSIBLE_VERSION=1.7.1
  - ANSIBLE_VERSION=1.7
  - ANSIBLE_VERSION=1.6.9
  - ANSIBLE_VERSION=1.6.8
  - ANSIBLE_VERSION=1.6.7
  - ANSIBLE_VERSION=1.6.6
  - ANSIBLE_VERSION=1.6.5
  - ANSIBLE_VERSION=1.6.4
  - ANSIBLE_VERSION=1.6.3
  - ANSIBLE_VERSION=1.6.2
  - ANSIBLE_VERSION=1.6.10
  - ANSIBLE_VERSION=1.6.1
  - ANSIBLE_VERSION=1.6
  - ANSIBLE_VERSION=1.5.5
  - ANSIBLE_VERSION=1.5.4
  - ANSIBLE_VERSION=1.5.3
  - ANSIBLE_VERSION=1.5.2
  - ANSIBLE_VERSION=1.5.1
  - ANSIBLE_VERSION=1.5
  - ANSIBLE_VERSION=1.4.5
  - ANSIBLE_VERSION=1.4.4
  - ANSIBLE_VERSION=1.4.3
  - ANSIBLE_VERSION=1.4.2
  - ANSIBLE_VERSION=1.4.1
  - ANSIBLE_VERSION=1.4

branches:
  only:
    - master

before_install:
  - sudo apt-get update -qq

  # Remove lxc-docker
  - sudo apt-get remove --purge lxc-docker || true

install:
  # Install Ansible.
  - if [ "$ANSIBLE_VERSION" = "latest" ]; then pip install ansible; else pip install ansible==$ANSIBLE_VERSION; fi

script:
  # Check the role/playbook's syntax.
  - ansible-playbook -i tests/inventory tests/test.yml --syntax-check

notifications:
  email: false
  hipchat:
    rooms:
      secure: GPUtM44MpgqN/3+TXw4Onp7TpF6YOKpVQkB/sfwGYS1oHUCkp2eb3eGGfJAIUtNxkfFVkdUxM/Bp9GMCnpVjJwRRZP6hYUmlpjCHl8CiK2MjbLvzV65qqBAqYl5bLzKkmmRdPiC31m9ixMe4TiAhJFBK1NoETOP1LkCJ04ezL6U=
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
