# tasks file for docker
---
- name: backported kernel | install
  apt:
    name: "{{ docker_backported_kernel_packages }}"
    state: "{{ apt_install_state | default('latest') }}"
  register: _backported_kernel_result
  tags:
    - docker-backported-kernel-install

- name: backported kernel | reboot
  command: >
    shutdown -r now
  async: 0
  poll: 0
  ignore_errors: true
  when: _backported_kernel_result is changed
  tags:
    - docker-backported-kernel-apply
    - docker-backported-kernel-reboot

- name: backported kernel | wait for server to come online
  wait_for:
    host: "{{ ansible_ssh_host | default(inventory_hostname) }}"
    port: "{{ ansible_ssh_port | default(22) }}"
    delay: 15
    timeout: 600
    state: started
  become: false
  when: _backported_kernel_result is changed
  connection: local
  tags:
    - docker-backported-kernel-apply
    - docker-backported-kernel-reboot
    - docker-backported-kernel-reboot-wait
