# tasks file for docker
---
- name: apt update
  apt:
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - docker
    - docker-apt
    - docker-apt-update

# TODO: Cleanup
- include: backported-kernel.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('12.04', '==')
  tags:
    - configuration
    - docker
    - docker-backported-kernel

- name: install | dependencies | pre
  apt:
    name: "{{ docker_dependencies_pre }}"
    state: "{{ apt_install_state | default('latest') }}"
  tags:
    - configuration
    - docker
    - docker-install-dependencies

- include: repository.yml
  tags:
    - configuration
    - docker
    - docker-repository

- name: install | dependencies
  apt:
    name: "{{ docker_dependencies }}"
    state: "{{ apt_install_state | default('latest') }}"
  notify: restart docker
  tags:
    - configuration
    - docker
    - docker-install

- name: configuration | update - /etc/default/docker
  template:
    src: etc/default/docker.j2
    dest: /etc/default/docker
    owner: root
    group: root
    mode: 0644
  notify: restart docker
  tags:
    - configuration
    - docker
    - docker-configuration

- name: start and enable service
  service:
    name: docker
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - configuration
    - docker
    - docker-start-enable-service

- include: ufw.yml
  tags:
    - configuration
    - docker
    - docker-ufw

- include: updatedb.yml
  tags:
    - configuration
    - docker
    - docker-updatedb
