# tasks file for docker
---
- name: apt update
  apt:
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - docker
    - docker-apt
    - docker-apt-update

- include: backported-kernel.yml
  when: ansible_distribution == 'Ubuntu' and ansible_distribution_version | version_compare('12.04', '==')
  tags:
    - configuration
    - docker
    - docker-backported-kernel

- name: install dependencies (pre)
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ docker_dependencies_pre }}"
  when: item != ''
  tags:
    - configuration
    - docker
    - docker-install-dependencies

- include: repository.yml
  tags:
    - configuration
    - docker
    - docker-repository

- name: install dependencies
  apt:
    name: "{{ item }}"
    state: latest
  with_items: "{{ docker_dependencies }}"
  notify: restart docker
  tags:
    - configuration
    - docker
    - docker-install

- name: update configuration file - /etc/default/docker
  template:
    src: etc/default/docker.j2
    dest: /etc/default/docker
    owner: root
    group: root
    mode: 0644
  notify: restart docker
  tags:
    - configuration
    - docker
    - docker-configuration

- name: start and enable service
  service:
    name: docker
    state: started
    enabled: true
  tags:
    - configuration
    - docker
    - docker-start-enable-service

- include: ufw.yml
  tags:
    - configuration
    - docker
    - docker-ufw

- include: updatedb.yml
  tags:
    - configuration
    - docker
    - docker-updatedb
