# tasks file
---
- name: repository | install dependencies (pre)
  ansible.builtin.apt:
    name: "{{ ' '.join(docker_dependencies_pre).split() }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - docker-repository-install-dependencies

- name: repository | (keyrings) directory | create
  ansible.builtin.file:
    path: "{{ docker_keyring_dst | dirname }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  tags:
    - docker-repository-keyrings-directory-create

- name: repository | (keyring) file | download
  ansible.builtin.apt_key:
    url: "{{ docker_keyring_src }}"
    keyring: "{{ docker_keyring_dst }}"
    state: present
  tags:
    - insync-repository-keyring-file-download

- name: repository | add
  ansible.builtin.apt_repository:
    repo: "{{ item.type }} {{ item.url }} {{ item.component }}"
    state: "{{ item.state | default('present') }}"
    update_cache: true
    mode: 0644
  with_items: "{{ docker_repositories }}"
  tags:
    - docker-repository-add
